#!/bin/sh

# LS
alias ls='ls --color=always --group-directories-first'
alias la='ls -ah --color=always --group-directories-first'
alias ll='ls -lah --color=always --group-directories-first'

# Random aliases
alias show_rozvrch='feh ~/Screenshots/Rozvrch_9.B.png &'
alias cr-file='cp ~/.local/share/univ/template '
alias ttyc='tty-clock -s -b -c -f "%a %d.%m.%y"'
alias pipes='pipes.sh -t 1'
alias pacman='pacman --color=always'
alias brave='brave --password-store=basic'
alias diff='diff --color=always'

# yt-dlp

alias ytdlp-audio='yt-dlp --extract-audio'
# My functions
function tdownvid() {
	yt-dlp --postprocessor-args "-ss $1 -to $2" "$3"
}

# Vim
alias vim='nvim'

# Terminal swallowing
alias feh='devour feh'
alias zathura='devour zathura'
alias mpv='devour mpv'

# Mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Directories
alias lbin='cd ~/.local/bin'
alias lshare='cd ~/.local/share'
alias lstate='cd ~/.local/state'
alias cdunst='cd ~/.config/dunst'
alias cdmenu='cd ~/.config/dmenu'
alias cdwm='cd ~/.config/dwm'
alias cfeh='cd ~/.config/feh'
alias cpicom='cd ~/.config/picom'
alias crofi='cd ~/.config/rofi'
alias cst='cd ~/.config/st'
alias csuck='cd ~/.config/suckless'
alias czsh='cd ~/.config/zsh'
alias hvid='cd ~/Videos'
alias hgam='cd ~/Games'
alias hdots='cd ~/dotfiles'
alias hdraw='cd ~/Drawings'
alias hgits='cd ~/gits'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias du='du -h'     # human-readable sizes

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"
