#!/bin/sh
export GDK_SCALE=1.5
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_STYLE_OVERRIDE="kvantum"
export ZDOTDIR=$HOME/.config/zsh
export ZSH_COMPDUMP=$ZDOTDIR/.zcompdump-$HOST
export CM_LAUNCHER="dmenu"
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
export PATH="/usr/lib/jvm/java-21-openjdk-bin/bin":$PATH
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share/nvim/mason/bin":$PATH
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export MANPAGER="less -R --use-color -Dd+r -Du+b"
export MANWIDTH=999
export GTK_THEME="Qogir-Dark"
export GOPATH="$HOME/.local/bin/go"
export PATH="${GOPATH}/bin":$PATH
export PATH="$HOME/.cargo/bin":$PATH
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"

# Clipmenu
export CM_SELECTIONS="clipboard"
export CM_DEBUG=0
export CM_OUTPUT_CLIP=0
export CM_MAX_CLIPS=100

# Arduino sketch menu
export AVR_PORT="/dev/ttyUSB0"
export AVR_FQBN="arduino:avr:mega"
