#!/bin/sh

# Directories
dotsdir=$HOME/dotfiles
configd=$HOME/.config
scriptd=$HOME/.local/bin/scripts
shared=$HOME/.local/share
stated=$HOME/.local/state
alattyd=$HOME/.config/alacritty
awsomed=$HOME/.config/awesome
dunstd=$HOME/.config/dunst
dwmdir=$HOME/.config/dwm
slbard=$HOME/.config/dwm/slbar
patchsd=$HOME/.confit/dwm/patches
fehbgd=$HOME/.config/feh
picomd=$HOME/.config/picom
rofid=$HOME/.config/rofi
awesomed=$HOME/.config/awesome
qtiled=$HOME/.config/qtile
zshdir=$HOME/.config/zsh

# Commands
rfdpy="rofi -sort -theme dmenu -refilter-timeout-limit 30000"
rfdmdpy="rofi -sort -theme dmenu -refilter-timeout-limit 30000 -dmenu -i -p $1"
dmdpy="dmenu -p $1"
