-- these are filetypes that are not actual files, but rather meta buffers
-- created by plugins or by neovim itself
return {
    'NvimTree',
    'Nvpunk',
    'NvpunkHealthcheck',
    'Outline',
    'TelescopePrompt',
    'Trouble',
    'aerial',
    'alpha',
    'dashboard',
    'help',
    'lazy',
    'lir',
    'neo-tree',
    'neo-tree-popup',
    'neogitstatus',
    'notify',
    'packer',
    'spectre_panel',
    'startify',
    'toggleterm',
    'vim',
}
