#!/bin/sh
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
export ZDOTDIR=$HOME/.config/zsh
export PATH="$HOME/.local/bin":$PATH
export XDG_CONFIG_HOME="$HOME/.config"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANWIDTH=999
export GTK_THEME="Qogir-Dark"
export PATH=$HOME/.cargo/bin:$PATH
export GOPATH=$HOME/.local/share/go
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave"
export QT_QPA_PLATFORMTHEME="qt5ct"
